print("hello World!")
print("my name is Bishwa Bandhu Parmar")
print("I am 20 years old")
print("I am a student of B.Tech in Computer Science and Engineering")
print("I am a student of Gaya College of Engineering, Gaya")
print("I am from Bihar")
print("I love to play cricket")
print("I love to play chess")
print("I love to play football")
