name = "Alice Wonderland"

print(" Length of name:", len(name))
print(" Name in uppercase:", name.upper())
print(" Name in lowercase:", name.lower())
print(" Name with first letter capitalized:", name.capitalize())
print(" Name with all words capitalized:", name.title())
print(" Name with 'A' replaced by 'O':", name.replace('A', 'O'))
print(" Name split into characters:", list(name))
print(" Name split into words:", name.split())
print(" Name starts with 'A':", name.startswith('A'))
print(" Name ends with 'e':", name.endswith('e'))
print(" Name is alphabetic:", name.isalpha())
print(" Name is numeric:", name.isnumeric())
print(" Name is alphanumeric:", name.isalnum())
print(" Name is decimal:", name.isdecimal())
print(" Name is whitespace:", name.isspace())
print(" Name is printable:", name.isprintable())
print(" Name is identifier:", name.isidentifier())
print(" Name is lower:", name.islower())
print(" Name is upper:", name.isupper())
print(" Name is title:", name.istitle())
print(" Name is mixed case:", not name.islower() and not name.isupper())
print(" Name is digit:", name.isdigit())
print(" Name is space:", name.isspace())
print(" Name is ASCII:", name.isascii())
print(" Name is decimal:", name.isdecimal())
print(" Name is numeric:", name.isnumeric())
print(" Name is printable:", name.isprintable())
# print(" Name is title:", name.istitle())